name: uam_contacts
description: "UAM Physics Department Contacts App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  url_launcher: ^6.2.5
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/avatar_placeholder.png
    - assets/my_map.png